version: '2'
services:

  # The Application
  app:
    build:
      context: ./Server
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./Server:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
      - "CORS_ALLOWED_ORIGIN=http://localhost:8080"      
  # The Web Server
  web:
    build:
      context: ./Server
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8080:80
  # The Database
  database:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
    ports:
        - "33061:3306"
volumes:
  dbdata:
